### ISSUE TITLE
[RDF/Features] Add new Features and run tests

### ISSUE THREAD

**Issue by Christovis** [florpi/GraphCosmologyNetwork#3]
1. Add new features such as: angular momentum, epoch of formation, environment, central density, Haas environment.
2. Run new tests of RDF and check for correlations and importance.

**Comment by florpi** [comment]
Also: 
4. Check feature importance avoiding correlated features (the first four)
5. PCA visualization.

**Comment by Christovis** [comment]
implement PCA into sklearn models and create flag to give the option to chose between input features and PCA's
